### ISSUE TITLE
2个bug

### ISSUE THREAD

**Issue by wlj901017** [targetcloud/baisibudejie#1]
关注模块中的推荐关注功能里面刷新功能有2个BUG
1.下拉刷新之后,立即/快速切换左边另一个未加载过数据的cell,会出现没有请求到数据,界面空白的bug
2.上拉加载之后,立即/快速切换左边另一个未加载过数据的cel,顶部header刷新的文字布局会下移,显示空白的bug

**Comment by targetcloud** [comment]
ths,refresh bug already fixed
